name: food_delivery_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  animate_do: ^4.2.0
  bloc: ^9.0.0
  carousel_slider: ^5.1.1
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  dots_indicator: ^4.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  go_router: ^15.2.0
  shared_preferences: ^2.5.3
  syncfusion_flutter_charts: ^30.2.4
  smooth_page_indicator: ^1.2.1
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins\Poppins-Regular.ttf
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: app_assets.dart
  field_prefix: null
  ignore_comments: true
  classname: AppAssets
